#!/usr/bin/env bash

set -e

# Ensure we are in the project root
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

echo "Building and installing kara..."

# 1. Build and Install
mkdir -p build
cd build
cmake .. \
    -DCMAKE_INSTALL_PREFIX="$HOME/.local" \
    -DCMAKE_BUILD_TYPE=Release \
    -DKDE_INSTALL_USE_QT_SYS_PATHS=OFF
make -j$(nproc)
make install
cd ..

# 2. Make environment changes permanent for Plasma
echo "Setting up environment variables for Plasma..."
ENV_FILE="$HOME/.config/plasma-workspace/env/kara.sh"
mkdir -p "$(dirname "$ENV_FILE")"

echo "Generating environment variables script..."

cat > "$ENV_FILE" << 'EOF'
# Generated by kara install.sh
export PATH="$HOME/.local/bin:$PATH"
export XDG_DATA_DIRS="$HOME/.local/share:${XDG_DATA_DIRS:-/usr/local/share:/usr/share}"
export XDG_CONFIG_DIRS="$HOME/.local/etc/xdg:${XDG_CONFIG_DIRS:-/etc/xdg}"
export QML2_IMPORT_PATH="$HOME/.local/lib64/qml:$HOME/.local/lib/qml:$HOME/.local/lib/x86_64-linux-gnu/qml:${QML2_IMPORT_PATH}"
export QT_PLUGIN_PATH="$HOME/.local/lib64/plugins:$HOME/.local/lib/plugins:$HOME/.local/lib/x86_64-linux-gnu/qml:${QT_PLUGIN_PATH}"
EOF

# Make it executable
chmod +x "$ENV_FILE"

# 3. Apply environment to current script
source "$ENV_FILE"

# 4. Restart Plasma Shell
echo "Restarting plasmashell with new environment..."
# We use setsid or nohup to ensure plasmashell keeps running after the script exits
# and we source the env file again just in case.
nohup bash -c "source '$ENV_FILE' && plasmashell --replace" > /dev/null 2>&1 &

echo "--------------------------------------------------"
echo "Installation complete!"
echo "The environment variables have been added to:"
echo "  $ENV_FILE"
echo "This ensures the plugin is found after logout/reboot."
echo "Plasmashell is being restarted in the background."
echo "--------------------------------------------------"
